[functions]
  external_node_modules = ["express"]
[build]
    functions = "functions"
    command = "npm install && npm run build && node node_modules/pug-cli/index.js views/ --out ./"
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "noindex"